version: "3.7"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./.volumes/mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: "root:root@tcp(mysql:3306)/mydb"
    depends_on:
      - mysql
    command: ["sh", "-c", "sleep 10 && ./app"]
